apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubedb-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-autoscaler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubedb-autoscaler.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/managed-by: kubedb.com
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - elasticsearches.kubedb.com
              - etcds.kubedb.com
              - mariadbs.kubedb.com
              - memcacheds.kubedb.com
              - mongodbs.kubedb.com
              - mysqls.kubedb.com
              - perconaxtradbs.kubedb.com
              - pgbouncers.kubedb.com
              - postgreses.kubedb.com
              - proxysqls.kubedb.com
              - redises.kubedb.com
      namespaceSelector: {}
